backend:
  name: github
  repo: yaeloss/yael-ca
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}