#!/usr/bin/env python3
"""Generate GitHub Pages-compatible redirects after Hugo has built the site.

Uses Hugo's resolved URLs, never guesses destinations for missing content.
Also exports a CSV of exact redirects for a future host with HTTP 301 support.
"""
import csv
import html
import json
import math
import sys
from pathlib import Path
from urllib.parse import unquote, urljoin


def build_redirects(manifest):
    redirects = {}
    for post in manifest["posts"]:
        slug = post["url"].removeprefix("/posts/").strip("/")
        if "/" in slug or not slug:
            continue
        redirects[f"/{slug}/"] = post["url"]
        redirects[f'/{post["date"]}/{slug}/'] = post["url"]
    for term in manifest["terms"]:
        prefix = {"tags": "tag", "categories": "category"}.get(term["taxonomy"])
        if not prefix:
            continue
        slug = term["url"].strip("/").split("/", 1)[1]
        sources = [f"/{prefix}/{slug}/"]
        if prefix == "tag":
            for old, new in manifest["tagMerges"].items():
                if slug == new:
                    sources += [f"/tag/{old}/", f"/tags/{old}/"]
        for source in sources:
            redirects[source] = term["url"]
            # WordPress default: 10 posts/page. These now live in one archive.
            for page in range(1, math.ceil(term["count"] / 10) + 1):
                redirects[f"{source}page/{page}/"] = term["url"]
    terms = {term["url"]: term for term in manifest["terms"]}
    for old, target in manifest.get("archiveMoves", {}).items():
        if old in terms or target not in terms:
            raise ValueError(f"Invalid archive move: {old} -> {target}")
        sources = [old, old.replace("/categories/", "/category/", 1)]
        for source in set(sources):
            redirects[source] = target
            for page in range(1, math.ceil(terms[target]["count"] / 10) + 1):
                redirects[f"{source}page/{page}/"] = target
    for page in range(1, math.ceil(len(manifest["posts"]) / 10) + 1):
        redirects[f"/page/{page}/"] = "/posts/"
    return redirects


def main(destination):
    root = Path(destination).resolve()
    manifest = json.loads((root / "legacy-redirects.json").read_text())
    redirects = build_redirects(manifest)
    written = []
    for source, target in sorted(redirects.items()):
        path = root / unquote(source).lstrip("/") / "index.html"
        target_path = root / unquote(target).lstrip("/") / "index.html"
        if not path.resolve().is_relative_to(root) or not target_path.is_file():
            raise ValueError(f"Invalid redirect: {source} -> {target}")
        # Never overwrite a real Hugo page or a user-provided alias.
        if path.exists() and "<!-- Generated by scripts/generate_redirects.py -->" not in path.read_text():
            continue
        canonical = html.escape(urljoin(manifest["baseURL"], target), quote=True)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            '<!doctype html><!-- Generated by scripts/generate_redirects.py -->'
            '<html lang="en"><head><meta charset="utf-8">'
            '<title>Page moved | Yaël Ossowski</title>'
            f'<link rel="canonical" href="{canonical}">'
            f'<meta http-equiv="refresh" content="0; url={canonical}">'
            f'</head><body><p>This page has moved. <a href="{canonical}">'
            'Continue to the article or archive.</a></p></body></html>\n'
        )
        written.append((source, target, 301))
    with (root / "redirects.csv").open("w", newline="") as output:
        writer = csv.writer(output)
        writer.writerow(["source", "target", "status"])
        writer.writerows(written)
    print(f"Generated {len(written)} static redirect pages (HTML refresh, not HTTP 301).")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "public")
